server:
  port: 8484

spring:
  profiles:
    include: oauth  #oauth 로그인 진행시 정보를 가져오기위해서
  security:

    oauth2:
        google:
          client-id: 890304175366-cg7t8bjavr2dt1ttf4ma2atl077n8i4r.apps.googleusercontent.com
          client-secret: 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
          redirect-uri: http://localhost:3000
          token-uri: https://oauth2.googleapis.com/token
          resource-uri: https://www.googleapis.com/oauth2/v2/userinfo



##kakao yml
#sns:
#  kakao:
#    app-key: 9745ed27734727993c6e32423cb9e24c
#    redirect-uri: http://localhost:3000


  jackson:
    serialization:
      fail-on-empty-beans: false

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/crescendo
    username: root
    password: mariadb
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    # SQL??? ?? ? ?? DBMS? ???? ??
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl? ???? ??
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # SQL ??? ????? ??? ?? ??
    database: mysql # DBMS ?? ??

logging:
  level:
    root: info
    org.hibernate.SQL: debug

jwt:
  secret: l+BNQ72ZaeWtKp5l/+dFOAtGOL/PQGH5GFGZIcxPuamk7aDrXW0YxR2J6hq1UE+kspImInqgfFy9gARxhCNQ0A==

file:
  upload:
    root-path: C:/crescendo/upload/
jackson:
  serialization:
    fail-on-empty-beans: false